prepare: Also pull the origin, tag-corrupted image
From an internal cache, since the canonical location has been garbage
collected:

  $ oc image info registry.redhat.io/redhat/redhat-operator-index@sha256:210fa4ca556f36688bcab0bf949b698618f44380dc8f1e8a214ee62474664b7d
  error: image "registry.redhat.io/redhat/redhat-operator-index@sha256:210fa4ca556f36688bcab0bf949b698618f44380dc8f1e8a214ee62474664b7d" not found: manifest unknown: manifest unknown